version: '3'

services:

  postgres:
    container_name: postgres
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: weblabb4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  weblabb4:
    container_name: weblabb4
    build:
      context: backend
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8080:8080"

volumes:
  postgres_data:
