spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/weblabb4
    username: postgres
    password: ${DATASOURCE_PASSWORD}
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET}